### ISSUE TITLE
是否考慮以 open source license 釋出

### ISSUE THREAD

**Issue by shouko** [aotter/howgersay#13]
覺得這個滿有趣的，有點想要 fork 自己的版本
請問這個專案有考慮加上 LICENSE 以 MIT 或 GPL 等方式允許改作嗎

**Comment by guyspy** [comment]
好的呦，等我下班後弄一下，code 寫得有點趕結構亂亂真害羞

**Comment by guyspy** [comment]
#16   搞定，歡迎 fork
